#Do not change the version number. This is important for updating and allowing a better user experience.
Version: 2
Messages:
  Prefix: "&5[&fFlashlightPlus&5]&r "
  FlashlightOnMsg: "&2Flashlight has been enabled!"
  FlashlightOffMsg: "&3Flashlight has been disabled!"
  NoPermMsg: "&cYou do not have permission to use this command!"
  CooldownMsg: "&cYou can only use this command ever 30 seconds!"
#All sign text must be 15 characters or less.
Sign:
  Line1: "&2[Flashlight]"
  Line2: "&fClick here"
  Line3: "&fto use"
  Line4: ""
Backend:
  Cooldown: 30
  Metrics: true