name: FlashlightPlus
author: FallenYouth # With the help of CraftThatBlock
version: ${project.version}
main: com.fallenyouth.FlashlightPlus.FlashlightPlus
description: Advanced Flashlight plugin for Minecraft

commands:
  flashlight:
    description: Toggles Flashlight

permissions:
  flashlight.use:
    description: Use of the flashlight
    default: op
  flashlight.use.on:
    description: Turns the flashlight on
    default: op
  flashlight.use.off:
    description: Turns flashlight off
    default: op
  flashlight.use.spawn:
    description: Spawns in Flashlight torch
    default: op
  flashlight.admin.reload:
    description: Reload the configuration file
    default: op
  flashlight.bypasscooldown:
    description: Allow bypass of the cool down
    default: op
  flashlight.use.torch:
    description: Allows use of the torch
    default: op
  flashlight.admin.sign:
    description: Ability to create FlashlightPlus sign
    default: op
