name: FlashlightPlus
author: FallenYouth # With the help of CraftThatBlock
version: ${project.version}
main: net.mattslab.FlashlightPlus.FlashlightPlus
description: Advanced Flashlight plugin for Minecraft

commands:
  flashlight:
    description: Toggles Flashlight
  fl:
    description: Alias of flashlightn command

permissions:
  flashlight.toggle:
    description: Allows use of the flashlight
    default: op
  flashlight.help:
    description: Brigns up Flashlight Menu
    default: op
  flashlight.spawn:
    description: Spawns in Flashlight torch
    default: op
  flashlight.spawn.others:
    description: Spawns a flashlight to others
    default: op
  flashlight.bypasscooldown:
    description: Allow bypass of the cool down
    default: op
  flashlight.use.torch:
    description: Allows use of the torch
    default: op
  flashlight.admin.reload:
    description: Reload the configuration file
    default: op
  flashlight.admin.sign:
    description: Ability to create FlashlightPlus sign
    default: op
